export const SCHEMA = {
    knowsLanguage: "https://schema.org/knowsLanguage",
    skills: "https://schema.org/skills",
    startDate: "https://schema.org/startDate",
    endDate: "https://schema.org/endDate",
    description: "https://schema.org/description",
    name: "https://schema.org/name",
    uri: "https://schema.org/uri",
    url: "https://schema.org/url",
    Corporation: "https://schema.org/Corporation",
    EducationalOrganization: "https://schema.org/EducationalOrganization",
    GovernmentOrganization: "https://schema.org/GovernmentOrganization",
    NGO: "https://schema.org/NGO",
    Organization: "https://schema.org/Organization",
    PerformingGroup: "https://schema.org/PerformingGroup",
    Project: "https://schema.org/Project",
    SportsOrganization: "https://schema.org/SportsOrganization",
} as const;
